spotify_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('LOCAL_DBT_USER') }}"
      pass: "{{ env_var('LOCAL_DBT_USER_PASS') }}"
      dbname: postgres
      schema: local_dbt_builds
    prod:
      type: postgres
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('PROD_DBT_USER') }}"
      pass: "{{ env_var('PROD_DBT_USER_PASS') }}"
      dbname: postgres
      schema: public