spotify_dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      dbname: postgres
      schema: local_dbt_builds
      # Env variables for local credentials (more secure approach possible?)
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('LOCAL_DBT_USER') }}"
      pass: "{{ env_var('LOCAL_DBT_USER_PASS') }}"
    prod:
      type: postgres
      dbname: postgres
      schema: public
      # Env variables for prod credentials (more secure approach possible?)
      host: "{{ env_var('DBT_HOST') }}"
      port: "{{ env_var('DBT_PORT') | int }}"
      user: "{{ env_var('PROD_DBT_USER') }}"
      pass: "{{ env_var('PROD_DBT_USER_PASS') }}"